"""
FormsLoaderMixin: loads Ext/Form.xml structures, links controls/events/attributes/commands,
and creates BINDS_TO/USED_IN relationships for UI/data bindings.
"""
from __future__ import annotations

from typing import Any, Dict, List
import logging

from config import settings
from .cypher_templates import (
    CYPHER_FORM_UPDATE_PROPS_REGULAR,
    CYPHER_FORM_UPDATE_PROPS_COMMONFORM,
    CYPHER_UPSERT_FORMCONTROL,
    CYPHER_LINK_HAS_CONTROL_REGULAR,
    CYPHER_LINK_HAS_CONTROL_COMMONFORM,
    CYPHER_LINK_HAS_CHILD_CONTROL,
    CYPHER_UPSERT_FORMEVENT,
    CYPHER_UPSERT_FORMEVENTACTION,
    CYPHER_LINK_HAS_EVENT_FORM,
    CYPHER_LINK_HAS_EVENT_COMMONFORM,
    CYPHER_LINK_HAS_EVENT_CONTROL,
    CYPHER_UPSERT_FORMATTR_AND_LINK_REGULAR,
    CYPHER_UPSERT_FORMATTR_AND_LINK_COMMONFORM,
    CYPHER_UPSERT_FORM_COMMAND_REGULAR,
    CYPHER_UPSERT_FORM_COMMAND_COMMONFORM,
    CYPHER_LINKS_TO_COMMAND,
    cypher_binds_to,
    cypher_used_in,
)

logger = logging.getLogger(__name__)


class FormsLoaderMixin:
    def load_form_definitions(self, rows: Dict[str, List[Dict[str, Any]]]) -> None:
        """
        Load parsed Ext/Form.xml structures into Neo4j using multiple small transactions
        to avoid long-running commits/timeouts.

        Expected 'rows' keys:
          - form_updates: [{form_qn, properties}]
          - controls: [{qn, name, type, properties}]
          - root_rel: [{form_qn, control_qn, order}]
          - child_rel: [{parent_qn, child_qn, order}]
          - events: [{qn, properties}]
          - event_rel: [{source_qn, source_label, event_qn}]
          - form_attributes: [{qn, form_qn, name, properties}]
          - form_commands: [{form_qn, cmd_qn, cmd_name, properties}]
          - form_command_usages: [{container_qn, cmd_qn, rel_key, via, button_id, button_name}]
          - data_bindings: list of {container_qn, target_qn, target_label, via, raw, resolved, resolution}
          - form_attribute_usages: [{consumer_qn, target_qn, ...}] (will be generated by resolver, or may be provided)
        """
        if not rows:
            return

        try:
            logger.info(
                "Form XCF batches: updates=%d, controls=%d, root_rel=%d, child_rel=%d, events=%d, event_actions=%d, event_rel=%d, form_attributes=%d",
                len(rows.get("form_updates") or []),
                len(rows.get("controls") or []),
                len(rows.get("root_rel") or []),
                len(rows.get("child_rel") or []),
                len(rows.get("events") or []),
                len(rows.get("event_actions") or []),
                len(rows.get("event_rel") or []),
                len(rows.get("form_attributes") or []),
            )
        except Exception:
            pass

        bs = settings.neo4j_batch_size
        def _chunks(lst: List[Dict[str, Any]]):
            return list(self._chunked(lst, bs))

        form_updates = rows.get("form_updates") or []
        controls = rows.get("controls") or []
        root_rel = rows.get("root_rel") or []
        child_rel = rows.get("child_rel") or []
        events = rows.get("events") or []
        event_actions = rows.get("event_actions") or []
        event_rel = rows.get("event_rel") or []
        form_attributes = rows.get("form_attributes") or []
        form_commands = rows.get("form_commands") or []
        form_command_usages = rows.get("form_command_usages") or []
        data_bindings = rows.get("data_bindings") or []
        form_attribute_usages = rows.get("form_attribute_usages") or []

        bindings_attr = [b for b in data_bindings if (b.get("target_label") == "Attribute")]
        bindings_dim  = [b for b in data_bindings if (b.get("target_label") == "Dimension")]
        bindings_res  = [b for b in data_bindings if (b.get("target_label") == "Resource")]
        bindings_fa   = [b for b in data_bindings if (b.get("target_label") == "FormAttribute")]
        bindings_mo   = [b for b in data_bindings if (b.get("target_label") == "MetadataObject")]

        with self.driver.session(database=settings.neo4j_database) as session:
            # Pass 1: node-creating operations — must complete before relations can MATCH them
            # (form_updates, controls, events, form_attributes, form_commands)
            node_colls = [
                ("form_updates",    form_updates),
                ("controls",        controls),
                ("events",          events),
                ("event_actions",   event_actions),
                ("form_attributes", form_attributes),
                ("form_commands",   form_commands),
            ]
            node_chunked = [(key, list(self._chunked(lst, bs))) for key, lst in node_colls]
            node_max = max((len(c) for _, c in node_chunked), default=0)
            if node_max:
                logger.info("Form definitions pass 1 (nodes): %d combined passes", node_max)
                for i in range(node_max):
                    payload = {key: (chunks[i] if i < len(chunks) else []) for key, chunks in node_chunked}
                    self._write(session, self._load_form_definitions_tx, payload)

            # Pass 2: relation-creating operations — all referenced nodes exist from pass 1
            # (root_rel, child_rel, event_rel, form_attribute_usages, form_command_usages)
            rel_colls = [
                ("root_rel",              root_rel),
                ("child_rel",             child_rel),
                ("event_rel",             event_rel),
                ("form_attribute_usages", form_attribute_usages),
                ("form_command_usages",   form_command_usages),
            ]
            rel_chunked = [(key, list(self._chunked(lst, bs))) for key, lst in rel_colls]
            rel_max = max((len(c) for _, c in rel_chunked), default=0)
            if rel_max:
                logger.info("Form definitions pass 2 (relations): %d combined passes", rel_max)
                for i in range(rel_max):
                    payload = {key: (chunks[i] if i < len(chunks) else []) for key, chunks in rel_chunked}
                    self._write(session, self._load_form_definitions_tx, payload)

            # 10) DataPath BINDS_TO edges (split by target label for index use)
            if bindings_attr:
                chunks = _chunks(bindings_attr)
                total = len(chunks)
                logger.info("Linking BINDS_TO (Attribute): %d", len(bindings_attr))
                for i, chunk in enumerate(chunks, 1):
                    logger.info("BINDS_TO Attribute chunk %d/%d (size=%d)", i, total, len(chunk))
                    self._write(session, self._load_form_bindings_tx, "Attribute", chunk)

            if bindings_dim:
                chunks = _chunks(bindings_dim)
                total = len(chunks)
                logger.info("Linking BINDS_TO (Dimension): %d", len(bindings_dim))
                for i, chunk in enumerate(chunks, 1):
                    logger.info("BINDS_TO Dimension chunk %d/%d (size=%d)", i, total, len(chunk))
                    self._write(session, self._load_form_bindings_tx, "Dimension", chunk)

            if bindings_res:
                chunks = _chunks(bindings_res)
                total = len(chunks)
                logger.info("Linking BINDS_TO (Resource): %d", len(bindings_res))
                for i, chunk in enumerate(chunks, 1):
                    logger.info("BINDS_TO Resource chunk %d/%d (size=%d)", i, total, len(chunk))
                    self._write(session, self._load_form_bindings_tx, "Resource", chunk)

            if bindings_fa:
                chunks = _chunks(bindings_fa)
                total = len(chunks)
                logger.info("Linking BINDS_TO (FormAttribute): %d", len(bindings_fa))
                for i, chunk in enumerate(chunks, 1):
                    logger.info("BINDS_TO FormAttribute chunk %d/%d (size=%d)", i, total, len(chunk))
                    self._write(session, self._load_form_bindings_tx, "FormAttribute", chunk)

            if bindings_mo:
                chunks = _chunks(bindings_mo)
                total = len(chunks)
                logger.info("Linking BINDS_TO (MetadataObject): %d", len(bindings_mo))
                for i, chunk in enumerate(chunks, 1):
                    logger.info("BINDS_TO MetadataObject chunk %d/%d (size=%d)", i, total, len(chunk))
                    self._write(session, self._load_form_bindings_tx, "MetadataObject", chunk)

    def _load_form_definitions_tx(self, tx, rows: Dict[str, List[Dict[str, Any]]]) -> None:
        """Transactional loader for XCF form structures."""
        # 1) Update Form node properties
        form_updates = rows.get("form_updates") or []
        if form_updates:
            bs = settings.neo4j_batch_size
            total = len(form_updates)
            chunks_total = (total + bs - 1) // bs
            logger.info("Updating Form nodes: %d", total)
            for i, chunk in enumerate(self._chunked(form_updates, bs), 1):
                logger.info("Form updates chunk %d/%d (size=%d)", i, chunks_total, len(chunk))
                cf_chunk   = [r for r in (chunk or []) if "/ОбщиеФормы/" in (r.get("form_qn") or "")]
                reg_chunk  = [r for r in (chunk or []) if "/ОбщиеФормы/" not in (r.get("form_qn") or "")]
                if reg_chunk:
                    tx.run(CYPHER_FORM_UPDATE_PROPS_REGULAR, rows=reg_chunk)
                if cf_chunk:
                    tx.run(CYPHER_FORM_UPDATE_PROPS_COMMONFORM, rows=cf_chunk)

        # 2) Upsert FormControl nodes
        controls = rows.get("controls") or []
        if controls:
            bs = settings.neo4j_batch_size
            total = len(controls)
            chunks_total = (total + bs - 1) // bs
            logger.info("Upserting FormControl nodes: %d", total)
            for i, chunk in enumerate(self._chunked(controls, bs), 1):
                logger.info("FormControl chunk %d/%d (size=%d)", i, chunks_total, len(chunk))
                tx.run(CYPHER_UPSERT_FORMCONTROL, rows=chunk)

        # 3) Root relations: (Form)-[:HAS_CONTROL]->(FormControl) or (MetadataObject)-[:HAS_CONTROL]->(FormControl) for CommonForms
        root_rel = rows.get("root_rel") or []
        if root_rel:
            bs = settings.neo4j_batch_size
            total = len(root_rel)
            chunks_total = (total + bs - 1) // bs
            logger.info("Linking root controls (HAS_CONTROL): %d", total)
            for i, chunk in enumerate(self._chunked(root_rel, bs), 1):
                logger.info("HAS_CONTROL root chunk %d/%d (size=%d)", i, chunks_total, len(chunk))
                cf_chunk   = [r for r in (chunk or []) if "/ОбщиеФормы/" in (r.get("form_qn") or "")]
                reg_chunk  = [r for r in (chunk or []) if "/ОбщиеФормы/" not in (r.get("form_qn") or "")]
                if reg_chunk:
                    tx.run(CYPHER_LINK_HAS_CONTROL_REGULAR, rows=reg_chunk)
                if cf_chunk:
                    tx.run(CYPHER_LINK_HAS_CONTROL_COMMONFORM, rows=cf_chunk)

        # 4) Child relations: (FormControl)-[:HAS_CHILD]->(FormControl)
        child_rel = rows.get("child_rel") or []
        if child_rel:
            bs = settings.neo4j_batch_size
            total = len(child_rel)
            chunks_total = (total + bs - 1) // bs
            logger.info("Linking child controls (HAS_CHILD): %d", total)
            for i, chunk in enumerate(self._chunked(child_rel, bs), 1):
                logger.info("HAS_CHILD chunk %d/%d (size=%d)", i, chunks_total, len(chunk))
                tx.run(CYPHER_LINK_HAS_CHILD_CONTROL, rows=chunk)

        # 5) Upsert FormEvent nodes
        events = rows.get("events") or []
        if events:
            bs = settings.neo4j_batch_size
            total = len(events)
            chunks_total = (total + bs - 1) // bs
            logger.info("Upserting FormEvent nodes: %d", total)
            for i, chunk in enumerate(self._chunked(events, bs), 1):
                logger.info("FormEvent chunk %d/%d (size=%d)", i, chunks_total, len(chunk))
                tx.run(CYPHER_UPSERT_FORMEVENT, rows=chunk)

        # 5a) Upsert FormEventAction nodes and HAS_EVENT_ACTION links
        ea_rows = rows.get("event_actions") or []
        if ea_rows:
            bs = settings.neo4j_batch_size
            total = len(ea_rows)
            chunks_total = (total + bs - 1) // bs
            logger.info("Upserting FormEventAction nodes: %d", total)
            for i, chunk in enumerate(self._chunked(ea_rows, bs), 1):
                logger.info("FormEventAction chunk %d/%d (size=%d)", i, chunks_total, len(chunk))
                tx.run(CYPHER_UPSERT_FORMEVENTACTION, rows=chunk)

        # 6) Event relations: (Form|FormControl)-[:HAS_EVENT]->(FormEvent) and CommonForms variant
        event_rel = rows.get("event_rel") or []
        if event_rel:
            bs = settings.neo4j_batch_size
            ev_form = [r for r in event_rel if r.get("source_label") == "Form"]
            ev_ctrl = [r for r in event_rel if r.get("source_label") == "FormControl"]
            if ev_form:
                total = len(ev_form)
                chunks_total = (total + bs - 1) // bs
                logger.info("Linking form-level events: %d", total)
                for i, chunk in enumerate(self._chunked(ev_form, bs), 1):
                    logger.info("HAS_EVENT (Form) chunk %d/%d (size=%d)", i, chunks_total, len(chunk))
                    cf_chunk   = [r for r in (chunk or []) if "/ОбщиеФормы/" in (r.get("source_qn") or "")]
                    reg_chunk  = [r for r in (chunk or []) if "/ОбщиеФормы/" not in (r.get("source_qn") or "")]
                    if reg_chunk:
                        tx.run(CYPHER_LINK_HAS_EVENT_FORM, rows=reg_chunk)
                    if cf_chunk:
                        tx.run(CYPHER_LINK_HAS_EVENT_COMMONFORM, rows=cf_chunk)
            if ev_ctrl:
                total = len(ev_ctrl)
                chunks_total = (total + bs - 1) // bs
                logger.info("Linking control-level events: %d", total)
                for i, chunk in enumerate(self._chunked(ev_ctrl, bs), 1):
                    logger.info("HAS_EVENT (FormControl) chunk %d/%d (size=%d)", i, chunks_total, len(chunk))
                    tx.run(CYPHER_LINK_HAS_EVENT_CONTROL, rows=chunk)

        # 7) Form attributes: (Form|MetadataObject)-[:HAS_FORM_ATTRIBUTE]->(FormAttribute)
        form_attributes = rows.get("form_attributes") or []
        if form_attributes:
            bs = settings.neo4j_batch_size
            total = len(form_attributes)
            chunks_total = (total + bs - 1) // bs
            logger.info("Upserting FormAttribute nodes and links: %d", total)
            for i, chunk in enumerate(self._chunked(form_attributes, bs), 1):
                logger.info("FormAttribute chunk %d/%d (size=%d)", i, chunks_total, len(chunk))
                cf_chunk   = [r for r in (chunk or []) if "/ОбщиеФормы/" in (r.get("form_qn") or "")]
                reg_chunk  = [r for r in (chunk or []) if "/ОбщиеФормы/" not in (r.get("form_qn") or "")]
                if reg_chunk:
                    tx.run(CYPHER_UPSERT_FORMATTR_AND_LINK_REGULAR, rows=reg_chunk)
                if cf_chunk:
                    tx.run(CYPHER_UPSERT_FORMATTR_AND_LINK_COMMONFORM, rows=cf_chunk)

        # 8) Form-level Commands (Form -> Command)
        form_cmds = rows.get("form_commands") or []
        if form_cmds:
            bs = settings.neo4j_batch_size
            total = len(form_cmds)
            chunks_total = (total + bs - 1) // bs
            logger.info("Upserting Form Commands in tx: %d", total)
            for i, chunk in enumerate(self._chunked(form_cmds, bs), 1):
                logger.info("Form Commands tx chunk %d/%d (size=%d)", i, chunks_total, len(chunk))
                cf_chunk   = [r for r in (chunk or []) if "/ОбщиеФормы/" in (r.get("form_qn") or "")]
                reg_chunk  = [r for r in (chunk or []) if "/ОбщиеФормы/" not in (r.get("form_qn") or "")]
                if reg_chunk:
                    tx.run(CYPHER_UPSERT_FORM_COMMAND_REGULAR, rows=reg_chunk)
                if cf_chunk:
                    tx.run(CYPHER_UPSERT_FORM_COMMAND_COMMONFORM, rows=cf_chunk)

        # 9) UI linkages (FormControl -> Command) via LINKS_TO_COMMAND
        usages = rows.get("form_command_usages") or []
        if usages:
            bs = settings.neo4j_batch_size
            total = len(usages)
            chunks_total = (total + bs - 1) // bs
            logger.info("Linking LINKS_TO_COMMAND in tx: %d", total)
            for i, chunk in enumerate(self._chunked(usages, bs), 1):
                logger.info("LINKS_TO_COMMAND tx chunk %d/%d (size=%d)", i, chunks_total, len(chunk))
                tx.run(CYPHER_LINKS_TO_COMMAND, rows=chunk)

        # 10) USED_IN for FormAttribute
        fa_usages = rows.get("form_attribute_usages") or []
        if fa_usages:
            bs = settings.neo4j_batch_size
            total = len(fa_usages)
            chunks_total = (total + bs - 1) // bs
            logger.info("Linking USED_IN (FormAttribute) in tx: %d", total)
            for i, chunk in enumerate(self._chunked(fa_usages, bs), 1):
                logger.info("USED_IN (FormAttribute) tx chunk %d/%d (size=%d)", i, chunks_total, len(chunk))
                tx.run(cypher_used_in("FormAttribute"), rows=chunk)

    def update_form_hashes(self, hash_rows: List[Dict]) -> None:
        """
        Update form_content_hash / base_form_hash on Form nodes.
        hash_rows: [{form_qn, form_content_hash, base_form_hash}] — None fields are skipped.
        """
        from .cypher_templates import CYPHER_UPDATE_FORM_HASHES
        for batch in self._chunked(hash_rows, settings.neo4j_batch_size):
            with self.driver.session(database=settings.neo4j_database) as session:
                session.run(CYPHER_UPDATE_FORM_HASHES, rows=batch)

    def _load_form_bindings_tx(self, tx, label: str, rows: List[Dict[str, Any]]) -> None:
        """
        Transactional upsert for BINDS_TO edges from FormControl to a typed target label.
        label must be one of: Attribute, Dimension, Resource, FormAttribute, MetadataObject.
        """
        if not rows:
            return
        if label not in {"Attribute", "Dimension", "Resource", "FormAttribute", "MetadataObject"}:
            raise ValueError(f"Unsupported label for BINDS_TO: {label}")
        tx.run(cypher_binds_to(label), rows=rows)